# Generated by Django 5.2.4 on 2025-07-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(verbose_name="Время окончания"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailing.message", verbose_name="Сообщение"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(to="mailing.recipient", verbose_name="Получатели"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(verbose_name="Время начала"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("completed", "Завершена"), ("created", "Создана"), ("started", "Запущена")],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
