# Generated by Django 5.2.4 on 2025-07-16 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"permissions": [("view_all_mailings", "Can view all mailings")]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"permissions": [("view_all_messages", "Can view all messages")]},
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={"permissions": [("view_all_recipients", "Can view all recipients")]},
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
