# Generated by Django 5.2.4 on 2025-07-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_message_mailing_message_owner_alter_mailing_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="mailing.mailing"
            ),
        ),
    ]
